/*eslint-disable */
export const PROJECTS = [
	{
		id: "dashboard",
		nombre: "projects.project-dashboard.name",
		link: "https://emiliosg23.github.io/dashboard/",
		descripcion: "projects.project-dashboard.description",
		lenguajes: ["javascript", "html", "css"],
		usos: "Uso de CORS para extracción de información de manera didáctica, JavaScript para la funcionalidad interna del sitio web, HTML para la estructuración, CSS junto a Bootstrap para la estilización de la página web",
	},
	{
		id: "landing",
		nombre: "projects.project-landing.name",
		link: "https://emiliosg23.github.io/landing/",
		descripcion: "projects.project-landing.description",
		lenguajes: ["html", "css"],
		usos: "Uso de HTML para la estructuración de la página, CSS para el estilo",
	},
	{
		id: "mpa",
		nombre: "projects.project-mpa.name",
		link: "https://axcelvillagran.github.io/mpa/",
		descripcion: "projects.project-mpa.description",
		lenguajes: ["typescript", "html", "angular"],
		usos: "Uso del framework Angular para el diseño del Frontend, que se basa en el lenguaje TypeScript",
	},
	{
		id: "flex-travel",
		nombre: "projects.project-flex-travel.name",
		link: "https://github.com/AxcelVillagran/FrontendLP",
		descripcion: "projects.project-flex-travel.description",
		lenguajes: ["javascript", "dart", "flutter", "express"],
		usos: "Uso del framework Flutter para Frontend, Express para Backend.",
	},
	{
		id: "catalogo",
		nombre: "projects.project-catalogo.name",
		link: "https://github.com/PaulaPeraltaA/Proyecto-P1-Estructuras-G6",
		descripcion: "projects.project-catalogo.description",
		lenguajes: ["java", "javafx"],
		usos: "Estructura de Datos (listas enlazadas), JavaFX, Archivos serializados",
	},
	{
		id: "visualizador",
		nombre: "projects.project-visualizador.name",
		link: "https://github.com/PaulaPeraltaA/Proyecto-P2---Estructuras--G6",
		descripcion: "projects.project-visualizador.description",
		lenguajes: ["java", "javafx"],
		usos: "JavaFX, Archivos serializados",
	},
	{
		id: "rover",
		nombre: "projects.project-rover.name",
		link: "https://github.com/JamesMalave/Proyecto-POO-G2",
		descripcion: "projects.project-rover.description",
		lenguajes: ["java", "javafx"],
		usos: "Interfaces, hilos (multithreading), JavaFX, Archivos serializados.",
	},
	{
		id: "laberinto_encantado",
		nombre: "projects.project-laberinto_encantado.name",
		link: "https://github.com/EmilioSG23/laberinto_encantado",
		descripcion: "projects.project-laberinto_encantado.description",
		lenguajes: ["c_sharp", "typescript", "unity"],
		usos: "Unity Engine, SocketIO, WebGL",
	},
];
