export const PROJECTS = [
    {
        id: "dashboard",
        nombre: "Dashboard",
        link: "https://emiliosg23.github.io/dashboard/",
        descripcion: "Página web que indica la temperatura, precipitacíon, rayos UV y otros datos posibles de los próximos 5 días de una ciudad del Ecuador, cuenta con un selector de la provincia y ciudades para su visualización. Además, muestra el monitoreo de amenazas de inundación que pueden ocurrir en el país. Estos datos son recopilados de https://www.gestionderiesgos.gob.ec/monitoreo-de-inundaciones/ mediante el mecanismo CORS para su uso didáctico.",
        lenguajes: ["javascript", "html", "css"],
        usos: "Uso de CORS para extracción de información de manera didáctica, JavaScript para la funcionalidad interna del sitio web, HTML para la estructuración, CSS junto a Bootstrap para la estilización de la página web",
    },
    {
        id: "landing",
        nombre: "Landing",
        link: "https://emiliosg23.github.io/landing/",
        descripcion: "Página de Landing referentes a videojuegos, basandose en plataformas como Steam. Lo relevante es el diseño de la página web. No cuenta con funcionalidad interna",
        lenguajes: ["html","css"],
        usos: "Uso de HTML para la estructuración de la página, CSS para el estilo",
    },
    {
        id: "mpa",
        nombre: "MPA",
        link: "https://axcelvillagran.github.io/mpa/",
        descripcion: "Proyecto en equipo realizado en Angular que presenta estadísticas de Speedrun (pasarse rápido un juego). La idea principal del proyecto está en el uso del framework Angular para la creación de componentes compartidos, interfaces y conexión a una base de datos Firebase.",
        lenguajes: ["typescript", "html", "angular"],
        usos: "Uso del framework Angular para el diseño del Frontend, que se basa en el lenguaje TypeScript",
    },
    {
        id: "flex-travel",
        nombre: "Flex & Travel",
        link: "https://github.com/AxcelVillagran/FrontendLP",
        descripcion: "Proyecto para aplicaciones móviles, centrado en impulsar el turismo en negocios de todo tipo. Se trabajó tanto la parte del Frontend, como la parte del Backend por separado. Para ver el backend del proyecto, visitar: https://github.com/Fausto-Briones/LP-Proyecto2",
        lenguajes: ["javascript", "dart", "flutter", "express"],
        usos: "Uso del framework Flutter para Frontend, Express para Backend.",
    },
    {
        id: "catalogo",
        nombre: "Catálogo de Videojuegos",
        link: "https://github.com/PaulaPeraltaA/Proyecto-P1-Estructuras-G6  ",
        descripcion: "El proyecto consiste en simular un catálogo de videojuegos estilo Steam, donde se hace uso de Estrucutra de Datos como las listas circulares enlazadas. Además, hay dos vistas: una para el usuario y otra para el administrador. Por último, existen diversas formas de búsqueda de videojuegos.",
        lenguajes: ["java", "javafx"],
        usos: "Estructura de Datos (listas enlazadas), JavaFX, Archivos serializados",
    },
    {
        id: "visualizador",
        nombre: "Visualizador de Archivos",
        link: "https://github.com/PaulaPeraltaA/Proyecto-P2---Estructuras--G6",
        descripcion: "Consiste en visualizar los archivos de una manera más general, donde el tamaña de un archivo/directorio ocupará más o menos espacio en el visualizador. El comportamiento del programa está basado en árboles multicaminos. Tiene dos modos de visualización: una por archivos y otra por extensiones de archivo.",
        lenguajes: ["java", "javafx"],
        usos: "JavaFX, Archivos serializados",
    },
    {
        id: "rover",
        nombre: "Simulación de Rovers",
        link: "https://github.com/JamesMalave/Proyecto-POO-G2",
        descripcion: "Este proyecto consiste en un simulador de dos róvers en Marte, uno solar y otro eólico. Hay cráteres en Marte donde se encuentran materias que serán sensados. El usuario mediante comandos, se puede mover alrededor del planeta, puede planificar rutas, entre otros. Además, se pueden usar los dos róvers al mismo tiempo gracias al Multithreading.",
        lenguajes: ["java", "javafx"],
        usos: "Interfaces, hilos (multithreading), JavaFX, Archivos serializados.",
    },
    {
        id: "laberinto_encantado",
        nombre: "Laberinto Encantado",
        link: "https://github.com/EmilioSG23/laberinto_encantado",
        descripcion: "Juego multijugador cooperativo y competitivo donde 4 equipos se enfrentan entre sí para lograr salir del laberinto. También puedes ver el backend en: https://github.com/domorales/laberinto_encantado_backend/ y el desarrollo completo en: https://domorales.github.io/portfolio-momentum/",
        lenguajes: ["c_sharp", "typescript", "unity"],
        usos: "Unity Engine, SocketIO, WebGL",
    }
]