/* eslint-disable */
export const SKILLS = [
	{
		id: "languages",
		name: "skills.skill-languages.title.full",
		shortName: "skills.skill-languages.title.short",
		values: [
			{
				id: "typescript",
				name: "TypeScript",
				color: "#3178C6",
				text: "white",
				display: true,
			},
			{
				id: "javascript",
				name: "JavaScript",
				color: "#f9a200",
				text: "black",
				display: true,
			},

			{
				id: "css",
				name: "CSS",
				color: "#004ce9",
				text: "white",
				display: true,
			},
			{
				id: "html",
				name: "HTML",
				color: "#ff4c1e",
				text: "white",
				display: true,
			},
			{
				id: "java",
				name: "Java",
				color: "white",
				text: "#c42626",
				display: true,
			},
			{
				id: "python",
				name: "Python",
				color: "#0081b4",
				text: "ffdd44",
				display: true,
			},
			{
				id: "c",
				name: "C",
				color: "#3d9bd5",
				text: "white",
				display: true,
			},
			{
				id: "php",
				name: "PhP",
				color: "#4f82b9",
				text: "black",
				display: false,
			},
			{
				id: "ruby",
				name: "Ruby",
				color: "#cc0700",
				text: "white",
				display: false,
			},
			{
				id: "dart",
				name: "Dart",
				color: "#00b8f8",
				text: "white",
				display: false,
			},
			{
				id: "rust",
				name: "Rust",
				color: "gray",
				text: "white",
				display: false,
			},
			{
				id: "c_sharp",
				name: "C#",
				color: "#400095",
				text: "white",
				display: true,
			},
		],
	},
	{
		id: "frontend",
		name: "skills.skill-frontend.title.full",
		shortName: "skills.skill-frontend.title.short",
		values: [
			{
				id: "astro",
				name: "Astro",
				color: "#e43a99",
				text: "white",
				display: true,
			},
			{
				id: "react",
				name: "React",
				color: "#61dafb",
				text: "black",
				display: true,
			},
			{
				id: "angular",
				name: "Angular",
				color: "#d32a2d",
				text: "white",
				display: true,
			},
			{
				id: "tailwind",
				name: "Tailwind CSS",
				color: "#36b7f0",
				text: "white",
				display: true,
			},
			{
				id: "ionic",
				name: "Ionic",
				color: "#008cff",
				text: "white",
				display: false,
			},
			{
				id: "flutter",
				name: "Flutter",
				color: "#00c6fd",
				text: "white",
				display: false,
			},
			{
				id: "unity",
				name: "Unity",
				color: "white",
				text: "black",
				display: true,
			},
		],
	},
	{
		id: "backend",
		name: "skills.skill-backend.title.full",
		shortName: "skills.skill-backend.title.short",
		values: [
			{
				id: "express",
				name: "Express",
				color: "#838383",
				text: "white",
				display: true,
			},
			{
				id: "nodejs",
				name: "NodeJS",
				color: "#52b05c",
				text: "black",
				display: true,
			},
			{
				id: "django",
				name: "Django",
				color: "white",
				text: "black",
				display: false,
			},
			{
				id: "springboot",
				name: "Springboot",
				color: "#8bc34a",
				text: "white",
				display: true,
			},
			{
				id: "socketio",
				name: "SocketIO",
				color: "white",
				text: "black",
				display: false,
			},
		],
	},
	{
		id: "others",
		name: "skills.skill-others.title.full",
		shortName: "skills.skill-others.title.short",
		values: [
			{
				id: "sql",
				name: "SQL",
				color: "#00bdf4",
				text: "black",
				display: true,
			},
			{
				id: "mysql",
				name: "MySQL",
				color: "#007aa4",
				text: "#de8638",
				display: true,
			},
			{
				id: "photoshop",
				name: "Photoshop",
				color: "#00c9ff",
				text: "#001721",
				display: true,
			},
			{
				id: "illustrator",
				name: "Illustrator",
				color: "#ff7c00",
				text: "#270b00",
				display: true,
			},
			{
				id: "figma",
				name: "Figma",
				color: "gray",
				text: "white",
				display: true,
			},
			{
				id: "vs-code",
				name: "Visual Studio Code",
				color: "#007acf",
				text: "white",
				display: true,
			},
			{
				id: "netbeans",
				name: "NetBeans",
				color: "white",
				text: "#0091ec",
				display: false,
			},
			{
				id: "javafx",
				name: "JavaFX",
				color: "white",
				text: "#5382a1",
				display: false,
			},
			{
				id: "scene-builder",
				name: "Scene Builder",
				color: "#ff8b00",
				text: "white",
				display: false,
			},
			{
				id: "render",
				name: "OnRender",
				color: "#191919",
				text: "white",
				display: false,
			},
			{
				id: "vercel",
				name: "Vercel",
				color: "#242424",
				text: "white",
				display: false,
			},
		],
	},
];
